host: "{{ router_host }}" #default -- 0.0.0.0
port: "{{ router_port }}" #default - 8000
#team_num: "{{ team_num }}" #Its used only for creating pool_size, default -- 20
redis_host: "{{ redis_host }}"  #default -- 127.0.0.1
redis_port: "{{ redis_port }}" #default -- 6379
redis_pool_size: 20 #default -- 20
#visualisation_url: "http://localhost:8080"
attack_logs: attacks.log
services:
  {% for service in services %}

- { fprefix: "{{ service.prefix }}", hostport: "127.0.0.1:{{ service.flag_handler_port }}" }
  {% endfor %}
