http_host: 127.0.0.1 #default -- 0.0.0.0
http_port: 5000 #default - 5000
redis_host: "127.0.0.1" #default -- 127.0.0.1
redis_port: "6379" #default -- 6379
redis_pool_size: 5 #default -- 5
flag_prefix: "F"
